# .terraform-docs.yml
formatter: "markdown table"
output:
  file: README.md
  mode: inject

# Sections to display (in order). Remove/add as you prefer.
sections:
  show:
    - header
    - requirements
    - providers
    - modules
    - resources
    - inputs
    - outputs

# Order tables (inputs/outputs) by ascending name
sort:
  enabled: true
  by: name
  order: asc

# Rendering settings
settings:
  anchor: true         # anchors in table titles
  default: true        # show default values
  required: true       # mark if an input is required
  sensitive: true      # mark sensitive ones
  type: true           # show variable type
  escape: true         # escape special characters
  indent: 2
  html: true
  hide-empty: true     # hide empty sections
