{{- if and .Values.serviceAccount.create .Values.serviceAccount.clusterWide -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "agent.serviceAccountName" . }}-role
rules:
  {{- toYaml .Values.serviceAccount.role.rules | nindent 3 }}
{{- end }}