{{- if and .Values.serviceAccount.create .Values.serviceAccount.clusterWide -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceAccount.name }}-binding
subjects:
  - kind: ServiceAccount
    name:  {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "agent.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}