args:
  %{ for arg in args }
- "${arg}"
  %{ endfor }

  %{ if length(service_account_annotations) > 0 }
serviceAccount:
  annotations:
    %{ for k, v in service_account_annotations }
    ${k}: "${v}"
    %{ endfor }
  %{ endif }

  %{ if length(pod_labels) > 0 }
podLabels:
  %{ for k, v in pod_labels }
  ${k}: "${v}"
  %{ endfor }
  %{ endif }

configuration:
  values:
  %{ for key, value in config_values }
    ${key}: "${value}"
  %{ endfor }

image:
  tag: "${image_tag}"

  %{ if length(init_scripts) > 0 }
initScripts:
  %{ for script in init_scripts }
- "${script}"
  %{ endfor }
  %{ endif }

