args:
  %{ for arg in args }
- "${arg}"
  %{ endfor }

  %{ if aws_iam_role_arn != "" || service_account_name != "" }
serviceAccount:
  create: true
  automount: true
  %{ if service_account_name != "" }
  name: "${service_account_name}"
  %{ endif }
  %{ if aws_iam_role_arn != "" }
  annotations:
    eks.amazonaws.com/role-arn: "${aws_iam_role_arn}"
  %{ endif }
  %{ endif }

configuration:
  values:
  %{ for key, value in config_values }
    ${key}: ${jsonencode(value)}
  %{ endfor }

image:
  tag: "${image_tag}"
  %{ if image_repository != "" }
  repository: "${image_repository}"
  %{ endif }

%{ if image_pull_secret_name != "" ~}
imagePullSecret:
  create: false
  name: "${image_pull_secret_name}"

%{ endif ~}
  %{ if length(init_scripts) > 0 }
initScripts:
  %{ for script in init_scripts }
- "${script}"
  %{ endfor }
  %{ endif }

%{ if worker_orchestrator ~}
worker:
  ${indent(2, yamlencode(worker))}
%{ endif ~}

%{ if liveness_probe != null ~}
livenessProbe:
  ${indent(2, yamlencode(liveness_probe))}
%{ endif ~}
%{ if readiness_probe != null ~}
readinessProbe:
  ${indent(2, yamlencode(readiness_probe))}
%{ endif ~}
