azure:
  subscriptionID: "${subscription_id}"
  resourceGroupName: "${resource_group_name}"
  tenantID: "${tenant_id}"
  hostedZoneName: "${hosted_zone_name}"
%{ if use_workload_identity ~}
  clientID: "${client_id}"
  useWorkloadIdentity: true
%{ endif ~}
