azure:
  subscriptionID: "${azure_subscription_id}"
  resourceGroupName: "${azure_resource_group_name}"
  clientID: "${azure_client_id}"
  tenantID: "${azure_tenant_id}"
  hostedZoneName: "${azure_hosted_zone_name}"
