azure:
  subscriptionID: "${subscription_id}"
  resourceGroupName: "${resource_group_name}"
  tenantID: "${tenant_id}"
  hostedZoneName: "${hosted_zone_name}"
  clientID: "${client_id}"
%{ if use_workload_identity ~}
  useWorkloadIdentity: true
%{ else ~}
  clientSecret: "${client_secret}"
%{ endif ~}
