args:
  - "--tags=$(TAGS)"
  - "--apikey=$(NP_API_KEY)"
  - "--runtime=host"
  - "--command-executor-env=NP_API_KEY=$(NP_API_KEY)"
  - "--command-executor-debug"
  - "--webserver-enabled"
  - "--command-executor-git-command-repos $(AGENT_REPOS)"

configuration:
  values:
    NP_API_KEY: "${api_key}"
    TAGS: "${tags}"
    AGENT_REPOS: "${agent_repos}"
    CLUSTER_NAME: "${cluster_name}"
    NAMESPACE: "${namespace}"
    DNS_TYPE: ”external_dns”


