provider:
  name: "${dns_provider_name}"

sources:
  - crd

domainFilters:
  - "${domain}"

policy: "upsert-only"
registry: "txt"
txtOwnerId: "${txt_owner_id}"
interval: "1m"
logLevel: "info"


env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: "external-dns-cloudflare"
        key: "api-token"

extraArgs:
%{ for arg in extra_args ~}
  - "${arg}"
%{ endfor ~}

serviceAccount:
  create: true
  name: "external-dns"

rbac:
  create: true

resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    memory: "256Mi"


securityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

podSecurityContext:
  fsGroup: 65534
  runAsNonRoot: true