provider:
  name: "${provider}"

sources:
  - crd

domainFilters:
  - "${domain}"

policy: "upsert-only"
registry: "txt"
txtOwnerId: "${txt_owner_id}"
interval: "1m"
logLevel: "info"

%{ if provider == "cloudflare" ~}
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: "external-dns-cloudflare"
        key: "api-token"
%{ endif ~}
extraArgs:
%{ for arg in extra_args ~}
  - "${arg}"
%{ endfor ~}

env: []

serviceAccount:
  create: true
%{ if provider == "google" ~}
  name: ${ksa_name}
  annotations:
    iam.gke.io/gcp-service-account: "${gsa_email}"
%{ else ~}
  name: "external-dns"
%{ endif ~}

rbac:
  create: true

resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    memory: "256Mi"


securityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

podSecurityContext:
  fsGroup: 65534
  runAsNonRoot: true