name: Commitlint

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  branch-name:
    if: ${{ !startsWith(github.head_ref, 'release-please--') }}
    uses: nullplatform/actions-nullplatform/.github/workflows/branch-validation.yml@main

  commitlint:
    if: ${{ !startsWith(github.head_ref, 'release-please--') }}
    uses: nullplatform/actions-nullplatform/.github/workflows/conventional-commit.yml@main
