name: Commitlint

on:
  pull_request:
    branches:
      - main

jobs:
  docs:
    uses: nullplatform/actions-nullplatform/.github/workflows/tf-docs.yml@main
  conventional-commit:
    needs: docs
    uses: nullplatform/actions-nullplatform/.github/workflows/conventional-commit.yml@main
