name: OpenTofu

on:
  pull_request:
    branches:
      - main
  push:
    branches: [ release-please--branches--main ]

jobs:
  validate:
    uses: nullplatform/actions-nullplatform/.github/workflows/tofu-lint.yml@main
