name: OpenTofu

on:
  pull_request:
    branches: [ main, 6.x ]
    types: [opened, synchronize, reopened]

jobs:
  validate:
    uses: nullplatform/actions-nullplatform/.github/workflows/tofu-lint.yml@main
