name: pipeline tofu
on:
  push:
    branches:
      - '**'
jobs:
  release:
    uses: nullplatform/actions-nullplatform-terraform/.github/workflows/release.yml@main
    if: github.ref_name == 'main'
    permissions:
      contents: write
      pull-requests: write