name: Security Scan

on:
  pull_request:
    branches:
      - main
      - 6.x
  push:
    branches:
      - main
      - 6.x
    paths:
      - '**/*.tf'

jobs:
  trivy:
    uses: nullplatform/actions-nullplatform/.github/workflows/trivy-tofu-scan.yml@main
    permissions:
      contents: read
      security-events: write
    with:
      upload_sarif: true
